name: CI

on:
  pull_request:
    branches: ["master", "main", "dev"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["master", "main", "dev"]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # With no caching at all the entire ci process takes 3m to complete!
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          make install

      - name: Test with pytest
        run: make test